image: archlinux
packages:
  - curl
  - unzip
  - msitools
  - zip
  - cmake-git
  - clang
  - llvm
  - lld
sources:
  - https://github.com/SokuDev/SokuMods
secrets:
  - 63d7a0ac-2635-4d42-9709-efcd2cf74858
tasks:
  - check: |
      [ "$GITHUB_REF" = "refs/heads/master" ] || complete-build
  - setup: |
      cd SokuMods
      sh setup.sh
      curl -s -O 'https://raw.githubusercontent.com/delthas/llvm-project/fix-winmsvc-rc/llvm/cmake/platforms/WinMsvc.cmake'
      curl -s -O 'https://raw.githubusercontent.com/delthas/llvm-project/fix-winmsvc-rc/llvm/cmake/platforms/ClangClCMakeCompileRules.cmake'
  - build: |
      cd SokuMods
      cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_TOOLCHAIN_FILE=WinMsvc.cmake -DHOST_ARCH=x86 -DLLVM_NATIVE_TOOLCHAIN=/usr -DMSVC_BASE=$PWD/msvc -DWINSDK_BASE=$PWD/winsdk -DWINSDK_VER=10.0.17763.0 -DBUILD_SOKU_STREAMING=FALSE -DINSTALL_AUTOPUNCH_DAT=TRUE .
      cmake --build .
      cmake --install .
      (cd install/SWRSToys && zip -r9 ../../swrstoys.zip *)
      (cd install/SokuEngine && zip -r9 ../../sokuengine.zip *)
  - deploy: |
      cd SokuMods
      scp -P 2222 -o StrictHostKeyChecking=no -q swrstoys.zip user@delthas.fr:/srv/http/blog/swrstoys.zip
      scp -P 2222 -o StrictHostKeyChecking=no -q sokuengine.zip user@delthas.fr:/srv/http/blog/sokuengine.zip
